class HomePageValidators:
    languages_dict = {
        "Deutsch (German)": [
            "简体中文 (Vereinfachtes Chinesisch)",
            "繁體中文 (Traditionelles Chinesisch)",
            "日本語 (Japanisch)",
            "한국어 (Koreanisch)",
            "ไทย (Thai)",
            "български (Bulgarisch)",
            "Čeština (Tschechisch)",
            "Dansk (Dänisch)",
            "English (Englisch)",
            "Español - España (Spanisch - Spanien)",
            "Español – Latinoamérica (Lateinamerikanisches Spanisch)",
            "Ελληνικά (Griechisch)",
            "Français (Französisch)",
            "Italiano (Italienisch)",
            "Bahasa Indonesia (Indonesisch)",
            "Magyar (Ungarisch)",
            "Nederlands (Niederländisch)",
            "Norsk (Norwegisch)",
            "Polski (Polnisch)",
            "Português (Portugiesisch – Portugal)",
            "Português - Brasil (Brasil. Portugiesisch)",
            "Română (Rumänisch)",
            "Русский (Russisch)",
            "Suomi (Finnisch)",
            "Svenska (Schwedisch)",
            "Türkçe (Türkisch)",
            "Tiếng Việt (Vietnamesisch)",
            "Українська (Ukrainisch)",
            "Ein Übersetzungsproblem melden",
        ],
        "Español - Latinoamérica (Spanish - Latin America)": [
            "简体中文 (Chino simplificado)",
            "繁體中文 (Chino tradicional)",
            "日本語 (Japonés)",
            "한국어 (Coreano)",
            "ไทย (Tailandés)",
            "български (Búlgaro)",
            "Čeština (Checo)",
            "Dansk (Danés)",
            "Deutsch (Alemán)",
            "English (Inglés)",
            "Español - España",
            "Ελληνικά (Griego)",
            "Français (Francés)",
            "Italiano",
            "Bahasa Indonesia (indonesio)",
            "Magyar (Húngaro)",
            "Nederlands (Holandés)",
            "Norsk (Noruego)",
            "Polski (Polaco)",
            "Português (Portugués de Portugal)",
            "Português - Brasil (Portugués - Brasil)",
            "Română (Rumano)",
            "Русский (Ruso)",
            "Suomi (Finés)",
            "Svenska (Sueco)",
            "Türkçe (Turco)",
            "Tiếng Việt (Vietnamita)",
            "Українська (Ucraniano)",
            "Informar de un error de traducción",
        ],
        "Português (Portuguese - Portugal)": [
            "简体中文 (Chinês Simplificado)",
            "繁體中文 (Chinês Tradicional)",
            "日本語 (Japonês)",
            "한국어 (Coreano)",
            "ไทย (Tailandês)",
            "Български (Búlgaro)",
            "Čeština (Checo)",
            "Dansk (Dinamarquês)",
            "Deutsch (Alemão)",
            "English (Inglês)",
            "Español-España (Espanhol de Espanha)",
            "Español-Latinoamérica (Espanhol da América Latina)",
            "Ελληνικά (Grego)",
            "Français (Francês)",
            "Italiano (Italiano)",
            "Bahasa Indonesia (Indonésio)",
            "Magyar (Húngaro)",
            "Nederlands (Holandês)",
            "Norsk (Norueguês)",
            "Polski (Polaco)",
            "Português (Brasil)",
            "Română (Romeno)",
            "Русский (Russo)",
            "Suomi (Finlandês)",
            "Svenska (Sueco)",
            "Türkçe (Turco)",
            "Tiếng Việt (Vietnamita)",
            "Українська (Ucraniano)",
            "Relatar problema de tradução",
        ],
        "Português - Brasil (Portuguese - Brazil)": [
            "简体中文 (Chinês simplificado)",
            "繁體中文 (Chinês tradicional)",
            "日本語 (Japonês)",
            "한국어 (Coreano)",
            "ไทย (Tailandês)",
            "Български (Búlgaro)",
            "Čeština (Tcheco)",
            "Dansk (Dinamarquês)",
            "Deutsch (Alemão)",
            "English (Inglês)",
            "Español-España (Espanhol — Espanha)",
            "Español-Latinoamérica (Espanhol — América Latina)",
            "Ελληνικά (Grego)",
            "Français (Francês)",
            "Italiano (Italiano)",
            "Bahasa Indonesia (Indonésio)",
            "Magyar (Húngaro)",
            "Nederlands (Holandês)",
            "Norsk (Norueguês)",
            "Polski (Polonês)",
            "Português (Portugal)",
            "Română (Romeno)",
            "Русский (Russo)",
            "Suomi (Finlandês)",
            "Svenska (Sueco)",
            "Türkçe (Turco)",
            "Tiếng Việt (Vietnamita)",
            "Українська (Ucraniano)",
            "Relatar um problema com a tradução",
        ],
    }
